### ISSUE TITLE
Exclusion of Children Ordered Fixtures from root level

### ISSUE THREAD

**Issue by umarch06** [Sebazzz/NUnitTestOrdering#5]
I was enjoying working on NUnitTestOrdering. Meanwhile, I am using OrderedTestFixtures and in each OrderedTestFixtures I have several other OrderedTestFixtures. 

So basically I can define that there are 3, 4 tabs of my website and in each tab I have 10-12 sub-tabs and I need to write tests in a way that there should be three parents under ordered fixtures as shown in the image below. Since I don't want the children to be on the same level as of their parents, they should be under children nodes. 

Can you please tell me how can I remove them from root level and restrict them only under parent?
Thanks for helping always!

**Comment by umarch-rltsquare** [comment]
any update on this?

**Comment by Sebazzz** [comment]
Not yet. Sorry. Could you perhaps create minimally reproducible scenario, preferably as test case in a fork from this repo?

**Comment by Sebazzz** [comment]
Can you please update whether you still experience this issue?

**Comment by Sebazzz** [comment]
Closed due to inactivity.
