### ISSUE TITLE
NUnitTestOrdering is pulling in all tests instead of just the tests for the defined test fixture

### ISSUE THREAD

**Issue by AutomationSifu** [Sebazzz/NUnitTestOrdering#7]
Hi Sebazzz,

I've updated all versions and dependencies and was able to install the NUnittestOrdering library in my current test automation project at work.

In the EnableTestOrdering.cs file I created a TestFixture with one test case just to test, as I slowly start to build test suites and it seems that all tests from the automation solution are being pulled when trying to run the tests just for the NUnitTestingOrdering suite, instead of just the tests for that one test fixture.

I'll provide some more details:

When defining the test ordering in the EnableTestOrdering file I only added one test fixture which is a login test with a few tests within the fixture.

But when I go to run the test suite using NUnitTestOrdering, it includes tests in my login test and all tests within the test automation solution.  Should I be using some type of exclusion filter or something?

Thanks!

**Comment by Sebazzz** [comment]
Several questions in order to understand the issue:

- Which NUnit version are you using?
- Which test runner are you using? If not NUnit console or GUI, please try that one.
- Please dump the test list using the `--explore` option of the NUnit command line test runner.

To clarify: The tests that are in the project are divided into an "Unordered" and "Ordered" tree. Everything that is not referenced in an ordered test fixture definition gets put in the unordered tree according to namespace order that is default behavior of NUnit.

**Comment by AutomationSifu** [comment]
**Version Numbers**:

NUnit                                        {3.9.0}                                                                                                                
NUnit3TestAdapter                   {3.9.0}                                                                                                        
NUnitTestOrdering                    {1.0.0-beta1}

I run the tests within Visual Studio
  -  In the Test Explorer (Visual Studio) , there is a way sort tests by trait and one of the traits is NUnitTestOrdering.

  -  I click on the NUnitTestOrdering trait and run the tests.

I'll run the --explore command and report back with feedback.  Is there a preference of NUnit console over the GUI?

Thanks!

**Comment by Sebazzz** [comment]
I prefer both the NUnit GUI and NUnit console because they fully show the test structure as its internal representation of NUnit itself. It also works much better for a hierarchical test structure like NUnit has (especially once you use NUnitTestOrdering).

**Comment by AutomationSifu** [comment]
More details below:  

I was able to download NUnit GUI and see the test fixtures displayed as Ordered and Ordered respectively (As you stated) when using the **NUnit Tree** filter/view.  I'm also able to run the TestFixture suites as successfully in NUnit GUI in the NUnit Tree filter/view

I noticed when I change the filter from the **NUnit Tree** to **Test List - By Assembly**, that the latter is how the tests were run in Visual Studio.

Should the TestFixture suites display the same way in Visual Studio as the do in NUnit Gui with the TestFixtures broken down into groups ?

My Automation project is checked into Source control so I'm not sure if that has something to do with the way the tests are picked up in Visual Studio.

I do have a warning message in Visual Studio next to the NUnitTestOrdering attribute:

**[Applied at:  at System.Envirnoment.GetStatckTrace(Exception e, Boolean needFileInfo)**

I've included the full error below:

`<property name='NUnitTestOrdering' value='Applied at:    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)   at System.Environment.get_StackTrace()   at NUnitTestOrdering.FixtureOrdering.EnableTestOrderingAttribute.ApplyOrdering(TestSuite root, Assembly assembly)
 in C:\Libraries\NUnitTestOrdering\src\NUnitTestOrdering\EnableTestOrderingAttribute.cs:line 72   at NUnit.Framework.Internal.Test.ApplyAttributesToTest(ICustomAttributeProvider provider)   at NUnit.Framework.Api.DefaultTestAssemblyBuilder.BuildTestAssembly(Assembly assembly, String assemblyName, IList`1 fixtures)   at NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(Assembly assembly, String assemblyPath, IDictionary`2 options)   at NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(String assemblyName, IDictionary`2 options)   at NUnit.Framework.Api.NUnitTestAssemblyRunner.Load(String assemblyName, IDictionary`2 settings)   at NUnit.Framework.Api.FrameworkController.LoadTests()   at NUnit.Framework.Api.FrameworkController.LoadTests(ICallbackEventHandler handler)   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark&amp; stackMark)   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark&amp; stackMark)   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)' />`

**Comment by Sebazzz** [comment]
Visual Studio traditionally didn't support hierarchical tests. This has been fixed in Visual Studio, but the test adapter may not support it yet. You should use the tree view mode in NUnit GUI. 

> I do have a warning message in Visual Studio next to the NUnitTestOrdering attribute

This is not an error, but a value that prints the stacktrace for diagnostic purposes.

**Comment by AutomationSifu** [comment]
Thanks for the information!  This item can be closed.
